project_id = "rqgrovumfgjwuhkthqxe"

[functions.generate-image]
verify_jwt = false

[functions.generate-copy]
verify_jwt = false

[functions.translate-image]
verify_jwt = false

[functions.suggest-scenes]
verify_jwt = false

[functions.detail-plan]
verify_jwt = false

[functions.optimize-product-info]
verify_jwt = false

[functions.manage-balance]
verify_jwt = false

[functions.admin-users]
verify_jwt = true

[functions.alipay-order]
verify_jwt = false

[functions.alipay-notify]
verify_jwt = false
