// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_SUPABASE_URL = 'https://rqgrovumfgjwuhkthqxe.supabase.co';
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_kR5Qt951QycXiDjppFSquQ_XODYlvpq';

function getProductionOverride() {
  if (typeof window === 'undefined') return null;

  const hostname = window.location.hostname;
  if (hostname === 'picspark.cn' || hostname === 'www.picspark.cn') {
    return {
      url: DEFAULT_SUPABASE_URL,
      key: DEFAULT_SUPABASE_PUBLISHABLE_KEY,
    };
  }

  return null;
}

const productionOverride = getProductionOverride();
const SUPABASE_URL = productionOverride?.url || import.meta.env.VITE_SUPABASE_URL || DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  productionOverride?.key || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || DEFAULT_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
